apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dns-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "dns-operator.labels" . | nindent 4 }}